const router = require('express').Router()
const { router: catalog } = require('../catalog/index')
const cardPayment = require('../cardPayment/index')
const transfer = require('../transfer/index')
const otp = require('../otp/index')
const service = require('../servicePay/index')
const movements = require('../movements/index')
const user = require('../user/index')
const policy = require('../policy/index')
const credit = require('../credit/index')
const savingsPurpose = require('../savingsPurpose/index')
const certificate = require('../certificate/index')

router.use('/otp', otp)
router.use('/catalog', catalog)
router.use('/cardPayment', cardPayment)
router.use('/transfer', transfer)
router.use('/services', service)
router.use('/movements', movements)
router.use('/user', user)
router.use('/policy', policy)
router.use('/credit', credit)
router.use('/savingsPurpose', savingsPurpose)
router.use('/certificate', certificate)

router.get('/', function (req, res) {
	res.status(200).json({ message: 'Estás conectado a nuestra API' })
})

module.exports = router